title: "Laptop: Dell XPS 13"
body:
- type: dropdown
  attributes:
    label: Releases
    description: Which releases did you test this hardware on?
    options:
      - "Linux Mint 21.x"
      - "Linux Mint 20.x"
      - "LMDE 5"
    multiple: true
  validations:
    required: true
- type: dropdown
  attributes:
    label: Compatibility
    description: Does it work well?
    options:
      - "Works perfectly"
      - "Works fine with some minor problems"
      - "Works partially"
      - "Doesn't work"
    multiple: true
  validations:
    required: true
- type: textarea
  attributes:
    label: Description of the hardware
    description: Describe your hardware. What works, what doesn't.
  validations:
    required: false
- type: textarea
  attributes:
    label: Optional - Notes
    description: Add details. Explain what you did to make it work (if applicable).
  validations:
    required: false